openapi: 3.1.0
info:
  version: 1.0.0
  title: ContactsApp
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: These are documentations of Contacts App
tags:
  - name: Contacts
    description: Operation about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  # - url: #посилання на задеплоєний сайт
paths:
  /contacts:
    get: 
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch: 
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete: 
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
      post:
        $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
      post:
        $ref: ../swagger/paths/auth/logout.yaml
  /auth/send-reset-email:
      post:
        $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
      post:
        $ref: ../swagger/paths/auth/reset-pwd.yaml
  /auth/confirm-oauth:
      post:
        $ref: ../swagger/paths/auth/confirm-oauth.yaml
  /auth/get-oauth-url:
    get: 
      $ref: ../swagger/paths/auth/get-oauth-url.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
